# Generated by Django 4.0.4 on 2022-04-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weather_state_name', models.CharField(max_length=200)),
                ('wind_direction_compass', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('applicable_date', models.DateTimeField(verbose_name='applicable_date')),
                ('min_temp', models.IntegerField(default=0)),
                ('max_temp', models.IntegerField(default=0)),
                ('the_temp', models.IntegerField(default=0)),
            ],
        ),
    ]
