# Generated by Django 4.0.4 on 2022-04-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_alter_weather_applicable_date_alter_weather_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='applicable_date',
            field=models.DateField(unique=True, verbose_name='applicable_date'),
        ),
    ]
